# predictions

> Machine learning models for predicting TR (template region) quality. Only a minority of random TR sequences are highly mutagenic, which is what makes prediction useful. Includes functions to score individual sequences, predict mutagenesis percentages, and optimize TR sequences using beam search to balance the function of the target protein, dgrRNA folding, and amino acid accessibility under mutagenesis.

In [ ]:
#| hide
%load_ext autoreload
%autoreload 2

In [ ]:
#| default_exp predictions

In [ ]:
#| export
import pickle
import warnings
import sklearn
import numpy as np
import pandas as pd
from dgrec.example_data import get_example_data_dir
import RNA
import os
from itertools import product
import matplotlib.pyplot as plt
from dgrec import encoding
from collections import defaultdict
from dgrec.utils import (codon_usage_ecoli, genetic_code, CODON_TO_AA,
                          codons_stop, codons_reaching_stop, AA, AA_IDS,
                          AA_TO_CODONS, nt_to_codons, codons_to_aa, nt_prot)

In [ ]:
# | export

_data_path=get_example_data_dir()
_model_name='e_TRSp_classifier.pkl'
_model_path=os.path.join(_data_path,_model_name)
model_Sp=pickle.load(open(_model_path,"rb"))

_model_name2='e_TRSpAvd_classifier.pkl'
_model_path2=os.path.join(_data_path,_model_name2)
model_Avd_Sp=pickle.load(open(_model_path2,"rb"))

_model_name_whole='whole_model.pkl'
_model_path_whole=os.path.join(_data_path,_model_name_whole)
model_whole=pickle.load(open(_model_path_whole,"rb"))

## Scoring functions

Predict TR quality scores and mutagenesis percentages for individual sequences or batches.

In [ ]:
# | export

def tr_score(TR_seq:str #A string of the TR DNA sequence
,features=1 #The classifier model, no need to specify it (one feature by default). If two: uses the two features model
         ):

    """Calculates the predicted score of a given TR sequence (1 = perfect TR and 0 = poorly-performing TR).  If features=2, returns the score according to each feature (better to have both high)."""
    encoded_TR=encoding.encode_tr_list([TR_seq],features)
    if features == 1:
        score=np.round(model_Sp.predict_proba([encoded_TR[0]])[:,1],decimals=2).item()
    elif features==2:
        score=[np.round(model_Sp.predict_proba([encoded_TR[0][:1]])[:,1],decimals=2).item(),np.round(model_Avd_Sp.predict_proba([encoded_TR[0][1:2]])[:,1],decimals=2).item()]
    return score

In [ ]:
TR_bad='TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG'
print('TR bad score =',tr_score(TR_bad))
TR_good='AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT'
print('TR good score =',tr_score(TR_good))

TR bad score = 0.23
TR good score = 0.84

In [ ]:
#| hide
# Tests for score
TR_bad = 'TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG'
TR_good = 'AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT'
s_bad = tr_score(TR_bad)
s_good = tr_score(TR_good)
assert isinstance(s_bad, float)
assert isinstance(s_good, float)
assert 0 <= s_bad <= 1, f"Score out of range: {s_bad}"
assert 0 <= s_good <= 1, f"Score out of range: {s_good}"
assert s_good > s_bad, "Good TR should score higher than bad TR"

# Two-feature score
s2 = tr_score(TR_good, features=2)
assert isinstance(s2, list) and len(s2) == 2
assert all(0 <= x <= 1 for x in s2)

In [ ]:
# | export
def tr_score_list(TR_seq_list:list, #A list of strings of TRs DNA sequences
TR_name_list:list, #A list of strings of TRs names
features=1 #The number of features to use
              ):
    """Calculates the score for every TR in the list and returns them in a dataframe format. If features=2, returns the score according to each feature (better to have both high)."""

    encoded_TR=encoding.encode_tr_list(TR_seq_list,features)
    if features==1:
        score=np.round(model_Sp.predict_proba(encoded_TR)[:,1],decimals=2)
        score_df=pd.DataFrame({
            'TR_Name':TR_name_list,
            'TR_Seq':TR_seq_list,
            'TR_Score':score
        })
        return score_df
    else:
        score_Sp=np.round(model_Sp.predict_proba(encoded_TR[:,:1])[:,1],decimals=2)
        score_Avd_Sp=np.round(model_Avd_Sp.predict_proba(encoded_TR[:,1:2])[:,1],decimals=2)
        score_df=pd.DataFrame({
            'TR_Name':TR_name_list,
            'TR_Seq':TR_seq_list,
            'TR_Score_Sp':score_Sp,
            'TR_Score_Avd':score_Avd_Sp
        })
        return score_df

In [ ]:
TR_bad=[
     'TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG',
     'AAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGGACAAAGGTCGTGATTTCGCTA',
    'GGTTTCTCTAAGGAGTCCATTCTGCCGAAGCGCAACTCCGACAAGCTGATCGCGCGTAAGAAGGACTGGG',
     'CAAGCTGATCGCGCGTAAGAAGGACTGGGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCG',
     'ACCCGATTGACTTCCTCGAGGCGAAGGGGTACAAGGAGGTGAAGAAGGATCTGATTATCAAGCTGCCGAA',
     'AGTACTCCCTGTTCGAGCTGGAGAATGGTCGTAAGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGG',
     'CAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGTTTTCTAAGCGCGTGATTCTGGCGG',
     'ACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGATAAGCCGATCCGTGAGCAGGCGGA',   
 ]

tr_score_list(TR_bad,['TR_bad_'+str(k) for k in range (1,9)])

    TR_Name                                             TR_Seq  TR_Score
0  TR_bad_1  TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACG...      0.23
1  TR_bad_2  AAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGT...      0.05
2  TR_bad_3  GGTTTCTCTAAGGAGTCCATTCTGCCGAAGCGCAACTCCGACAAGC...      0.00
3  TR_bad_4  CAAGCTGATCGCGCGTAAGAAGGACTGGGATCCGAAGAAGTACGGT...      0.00
4  TR_bad_5  ACCCGATTGACTTCCTCGAGGCGAAGGGGTACAAGGAGGTGAAGAA...      0.01
5  TR_bad_6  AGTACTCCCTGTTCGAGCTGGAGAATGGTCGTAAGCGTATGCTGGC...      0.08
6  TR_bad_7  CAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGT...      0.06
7  TR_bad_8  ACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGA...      0.12

In [ ]:
#| hide
# Tests for score_list
TR_test = ['AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT',
           'TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG']
result_df = tr_score_list(TR_test, ['good', 'bad'])
assert 'TR_Score' in result_df.columns
assert len(result_df) == 2
assert result_df.iloc[0]['TR_Score'] > result_df.iloc[1]['TR_Score']

# Test features=2 mode
result_df2 = tr_score_list(TR_test, ['good', 'bad'], features=2)
assert 'TR_Score_Sp' in result_df2.columns
assert 'TR_Score_Avd' in result_df2.columns
assert len(result_df2) == 2

In [ ]:
TR_good=[
     'AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT',
     'TCAAACATTATGAATTTCTTCAAAACCGAAATCACCTTAGCGAATGGCGAAATTCGTAAACGCCCTCTGA',
     'ATGCCTCAAGTAAACATCGTTAAAAAGACTGAGGTGCAGACTGGCGGTTTCTCTAAGGAGTCCATTCTGC',
     'GGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCGTACTCTGTTCTGGTGGTCGCCAAGGTC',
     'AGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAA',
     'GCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAACTTCCTGTACCTGGCCTCGCACTACGAG',
     'CAGAAGCAGCTGTTCGTGGAGCAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGTTTT',
     'CTAAGCGCGTGATTCTGGCGGACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGATAA'
     ]

tr_score_list(TR_good,['TR_good_'+str(k) for k in range (1,9)])

     TR_Name                                             TR_Seq  TR_Score
0  TR_good_1  AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAA...      0.84
1  TR_good_2  TCAAACATTATGAATTTCTTCAAAACCGAAATCACCTTAGCGAATG...      0.82
2  TR_good_3  ATGCCTCAAGTAAACATCGTTAAAAAGACTGAGGTGCAGACTGGCG...      0.76
3  TR_good_4  GGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCGTAC...      0.74
4  TR_good_5  AGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGGGAACGAGTT...      0.83
5  TR_good_6  GCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAACTTC...      0.55
6  TR_good_7  CAGAAGCAGCTGTTCGTGGAGCAGCACAAGCACTACCTGGACGAGA...      0.81
7  TR_good_8  CTAAGCGCGTGATTCTGGCGGACGCGAATCTGGATAAGGTCCTGTC...      0.81

In [ ]:
TR_bad=[
     'TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG',
     'AAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGGACAAAGGTCGTGATTTCGCTA',
    'GGTTTCTCTAAGGAGTCCATTCTGCCGAAGCGCAACTCCGACAAGCTGATCGCGCGTAAGAAGGACTGGG',
     'CAAGCTGATCGCGCGTAAGAAGGACTGGGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCG',
     'ACCCGATTGACTTCCTCGAGGCGAAGGGGTACAAGGAGGTGAAGAAGGATCTGATTATCAAGCTGCCGAA',
     'AGTACTCCCTGTTCGAGCTGGAGAATGGTCGTAAGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGG',
     'CAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGTTTTCTAAGCGCGTGATTCTGGCGG',
     'ACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGATAAGCCGATCCGTGAGCAGGCGGA',   
 ]

tr_score_list(TR_bad,['TR_bad_'+str(k) for k in range (1,9)],2)

    TR_Name  ... TR_Score_Avd
0  TR_bad_1  ...         0.63
1  TR_bad_2  ...         0.42
2  TR_bad_3  ...         0.30
3  TR_bad_4  ...         0.51
4  TR_bad_5  ...         0.59
5  TR_bad_6  ...         0.54
6  TR_bad_7  ...         0.29
7  TR_bad_8  ...         0.04

[8 rows x 4 columns]

In [ ]:
TR_good=[
     'AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT',
     'TCAAACATTATGAATTTCTTCAAAACCGAAATCACCTTAGCGAATGGCGAAATTCGTAAACGCCCTCTGA',
     'ATGCCTCAAGTAAACATCGTTAAAAAGACTGAGGTGCAGACTGGCGGTTTCTCTAAGGAGTCCATTCTGC',
     'GGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCGTACTCTGTTCTGGTGGTCGCCAAGGTC',
     'AGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAA',
     'GCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAACTTCCTGTACCTGGCCTCGCACTACGAG',
     'CAGAAGCAGCTGTTCGTGGAGCAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGTTTT',
     'CTAAGCGCGTGATTCTGGCGGACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGATAA'
     ]

tr_score_list(TR_good,['TR_good_'+str(k) for k in range (1,9)],2)

     TR_Name  ... TR_Score_Avd
0  TR_good_1  ...         0.80
1  TR_good_2  ...         0.78
2  TR_good_3  ...         0.84
3  TR_good_4  ...         0.75
4  TR_good_5  ...         0.88
5  TR_good_6  ...         0.58
6  TR_good_7  ...         0.34
7  TR_good_8  ...         0.82

[8 rows x 4 columns]

In [ ]:
# | export
def tr_mutagenesis_percentage(TR_seq:str #A string of the TR DNA sequence
         ):

    """Calculates the predicted DGR mutagenesis percentage of a given TR sequence (100 = perfect TR and 0 = poorly-performing TR)."""
    encoded_TR=encoding.encode_tr_list([TR_seq],2)
    rate=model_whole.predict(encoded_TR)[0]
    return 10**rate

In [ ]:
# | export
def tr_mutagenesis_percentage_list(TR_seq_list:list, #A list of strings of TRs DNA sequences
TR_name_list:list, #A list of strings of TRs names
              ):
    """Calculates the predicted DGR mutagenesis percentage for every TR in the list and returns them in a dataframe format"""

    encoded_TR=encoding.encode_tr_list(TR_seq_list,2)
    rates=model_whole.predict(encoded_TR)
    score_df=pd.DataFrame({
        'TR_Name':TR_name_list,
        'TR_Seq':TR_seq_list,
        'TR_rates':10**rates
    })
    return score_df

In [ ]:
# | export
#Deprecated aliases, kept so that code written against the old names keeps working.
def score(*args, **kwargs):
    "Deprecated alias for `tr_score`."
    warnings.warn("score() is deprecated; use tr_score().", DeprecationWarning, stacklevel=2)
    return tr_score(*args, **kwargs)

def score_list(*args, **kwargs):
    "Deprecated alias for `tr_score_list`."
    warnings.warn("score_list() is deprecated; use tr_score_list().", DeprecationWarning, stacklevel=2)
    return tr_score_list(*args, **kwargs)

def DGR_percentage(*args, **kwargs):
    "Deprecated alias for `tr_mutagenesis_percentage`."
    warnings.warn("DGR_percentage() is deprecated; use tr_mutagenesis_percentage().", DeprecationWarning, stacklevel=2)
    return tr_mutagenesis_percentage(*args, **kwargs)

def DGR_percentage_list(*args, **kwargs):
    "Deprecated alias for `tr_mutagenesis_percentage_list`."
    warnings.warn("DGR_percentage_list() is deprecated; use tr_mutagenesis_percentage_list().", DeprecationWarning, stacklevel=2)
    return tr_mutagenesis_percentage_list(*args, **kwargs)

In [ ]:
TR_bad=[
     'TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG',
     'AAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGGACAAAGGTCGTGATTTCGCTA',
    'GGTTTCTCTAAGGAGTCCATTCTGCCGAAGCGCAACTCCGACAAGCTGATCGCGCGTAAGAAGGACTGGG',
     'CAAGCTGATCGCGCGTAAGAAGGACTGGGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCG',
     'ACCCGATTGACTTCCTCGAGGCGAAGGGGTACAAGGAGGTGAAGAAGGATCTGATTATCAAGCTGCCGAA',
     'AGTACTCCCTGTTCGAGCTGGAGAATGGTCGTAAGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGG',
     'CAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGTTTTCTAAGCGCGTGATTCTGGCGG',
     'ACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGATAAGCCGATCCGTGAGCAGGCGGA',   
 ]

tr_mutagenesis_percentage_list(TR_bad,['TR_bad_'+str(k) for k in range (1,9)])

    TR_Name                                             TR_Seq  TR_rates
0  TR_bad_1  TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACG...  0.427049
1  TR_bad_2  AAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGT...  0.110769
2  TR_bad_3  GGTTTCTCTAAGGAGTCCATTCTGCCGAAGCGCAACTCCGACAAGC...  0.019986
3  TR_bad_4  CAAGCTGATCGCGCGTAAGAAGGACTGGGATCCGAAGAAGTACGGT...  0.025612
4  TR_bad_5  ACCCGATTGACTTCCTCGAGGCGAAGGGGTACAAGGAGGTGAAGAA...  0.045752
5  TR_bad_6  AGTACTCCCTGTTCGAGCTGGAGAATGGTCGTAAGCGTATGCTGGC...  0.172833
6  TR_bad_7  CAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGT...  0.092111
7  TR_bad_8  ACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGA...  0.039965

In [ ]:
TR_good=[
     'AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT',
     'TCAAACATTATGAATTTCTTCAAAACCGAAATCACCTTAGCGAATGGCGAAATTCGTAAACGCCCTCTGA',
     'ATGCCTCAAGTAAACATCGTTAAAAAGACTGAGGTGCAGACTGGCGGTTTCTCTAAGGAGTCCATTCTGC',
     'GGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCGTACTCTGTTCTGGTGGTCGCCAAGGTC',
     'AGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAA',
     'GCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAACTTCCTGTACCTGGCCTCGCACTACGAG',
     'CAGAAGCAGCTGTTCGTGGAGCAGCACAAGCACTACCTGGACGAGATTATTGAGCAGATTTCTGAGTTTT',
     'CTAAGCGCGTGATTCTGGCGGACGCGAATCTGGATAAGGTCCTGTCTGCCTACAATAAGCACCGTGATAA'
     ]

tr_mutagenesis_percentage_list(TR_good,['TR_good_'+str(k) for k in range (1,9)])

     TR_Name                                             TR_Seq  TR_rates
0  TR_good_1  AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAA...  3.067841
1  TR_good_2  TCAAACATTATGAATTTCTTCAAAACCGAAATCACCTTAGCGAATG...  2.721600
2  TR_good_3  ATGCCTCAAGTAAACATCGTTAAAAAGACTGAGGTGCAGACTGGCG...  2.808427
3  TR_good_4  GGATCCGAAGAAGTACGGTGGCTTCGATTCTCCGACCGTGGCGTAC...  1.919474
4  TR_good_5  AGCGTATGCTGGCGTCTGCGGGTGAGCTGCAGAAGGGGAACGAGTT...  4.142115
5  TR_good_6  GCAGAAGGGGAACGAGTTGGCCCTTCCGTCCAAGTACGTGAACTTC...  0.811313
6  TR_good_7  CAGAAGCAGCTGTTCGTGGAGCAGCACAAGCACTACCTGGACGAGA...  0.940305
7  TR_good_8  CTAAGCGCGTGATTCTGGCGGACGCGAATCTGGATAAGGTCCTGTC...  3.040041

In [ ]:
#| hide
# Tests for DGR_percentage
TR_good_test = 'AAATGATCGCCAAATCTGAACAGGAAATTGGCAAAGCAACCGCTAAATACTTTTTCTACTCAAACATTAT'
pct = tr_mutagenesis_percentage(TR_good_test)
assert pct > 0, "DGR_percentage should be positive for a good TR"

# Comparative test: good TR should have higher percentage than bad TR
TR_bad_test = 'TTAGCGAATGGCGAAATTCGTAAACGCCCTCTGATCGAAACCAACGGCGAAACGGGTGAGATCGTGTGGG'
pct_bad = tr_mutagenesis_percentage(TR_bad_test)
assert pct > pct_bad, "Good TR should have higher DGR percentage than bad TR"

## Sequence optimization utilities

Helper functions for codon manipulation and Pareto-optimal sequence selection.

In [ ]:
# | export
# | hide

def pareto_front(sequences #Dataframe containing a sequence and its two scores
                ):
    """
    Keep only Pareto-optimal sequences:
    no other sequence has both scores >= and at least one strictly greater.
    Args:
        sequences (DataFrame): A dataframe of sequences and their two scores.
        
    Returns:
        pareto: the list of rows corresponding to pareto optima (no sequence with both scores higher).
    """
    pareto = []
    for s in sequences:
        dominated = False
        for t in sequences:
            if (t["Score_TRSp"] >= s["Score_TRSp"] and
                t["Score_TRSpAvd"] >= s["Score_TRSpAvd"] and
                (t["Score_TRSp"] > s["Score_TRSp"] or
                 t["Score_TRSpAvd"] > s["Score_TRSpAvd"])):
                dominated = True
                break
        if not dominated:
            pareto.append(s)
    return pareto

def codons_compatible_with_AA(target_aa):
    """
    Return all codons X such that replacing any 'A' in X by {A,C,G,T}
    can yield a codon encoding target_aa.
    """
    compatible = []

    for codon, aa in genetic_code.items():
        if aa != target_aa:
            continue

        # For this "real" codon, generate all abstract codons
        # where any non-A position must match, and A can stand for anything
        abstract = []
        for nt in codon:
            if nt == "A":
                abstract.append(["A"])  # must stay A in abstract
            else:
                abstract.append([nt, "A"])  # could have been wildcard A

        for triplet in product(*abstract):
            compatible.append("".join(triplet))

    return set(compatible)

def mutate_adenine(codon):
    """Generate all possible codons by mutating adenine (A) to T, C, or G."""
    mutations = []
    for i, base in enumerate(codon):
        if base == 'A':
            for new_base in ['T', 'C', 'G']:
                mutated_codon = codon[:i] + new_base + codon[i+1:]
                mutations.append(mutated_codon)
    return mutations

def get_aa_by_adenine_mutation(codon):
    """Return the list of unique amino acids reachable by adenine mutation in the codon."""
    mutations = mutate_adenine(codon)
    unique_aa = set()

    for mutated_codon in mutations:
        aa = genetic_code.get(mutated_codon, None)
        if aa is not None:
            unique_aa.add(aa)

    return sorted(unique_aa)



def _valid_seq_reach_AAs(
    seq,
    dict_allowed=None,
    dict_allowed_max_min=None,
    frame_offset=0,
    freq_min=0.2,
    codon_usage=codon_usage_ecoli
):
    """Checks whether a DNA sequence can reach a set of target amino acids through adenine mutagenesis
    at each codon position."""
    # No constraints → original sequence only
    if not dict_allowed:
        return [seq]

    # Store allowed codons per position
    allowed_codons_per_pos = {}

    for i, allowed_aas in dict_allowed.items():
        # Start with codons compatible with first AA
        candidate_codons = set(
            codons_compatible_with_AA(allowed_aas[0])
        )

        # Intersect with other allowed AAs
        for aa in allowed_aas[1:]:
            candidate_codons &= set(
                codons_compatible_with_AA(aa)
            )

        # Apply codon usage filter
        filtered_codons = []
        for codon in candidate_codons:
            aa = genetic_code.get(codon)
            if aa not in codon_usage:
                continue
            if codon_usage[aa].get(codon, 0) > freq_min:
                filtered_codons.append(codon)
        # Check for codon that maximizes or minimizes diversity at that position, as indicated by dict_allowed_max_min
        if dict_allowed_max_min!=None and i in dict_allowed_max_min:
            if dict_allowed_max_min[i]=='max':
                L=[]
                for codon in filtered_codons: 
                    L.append(len(get_aa_by_adenine_mutation(codon)))
                filtered_codons=[filtered_codons[k] for k in range(len(L)) if L[k]==max(L)]
            elif dict_allowed_max_min[i]=='min':
                L=[]
                for codon in filtered_codons: 
                    L.append(len(get_aa_by_adenine_mutation(codon)))
                filtered_codons=[filtered_codons[k] for k in range(len(L)) if L[k]==min(L)]
        # If no valid codons → no valid sequences at all
        if not filtered_codons:
            warnings.warn("No codon satisfies the requested amino-acid constraints at this position; returning no sequences.", stacklevel=2)
            return []

        allowed_codons_per_pos[i] = filtered_codons

    # Generate all combinations of codons across positions
    positions = sorted(allowed_codons_per_pos.keys())
    codon_combinations = product(
        *[allowed_codons_per_pos[i] for i in positions]
    )

    variants = []

    for combo in codon_combinations:
        new_seq = list(seq)
        for i, codon in zip(positions, combo):
            start = frame_offset + i * 3
            new_seq[start:start + 3] = codon
        variants.append("".join(new_seq))

    return variants

        
    
def _propose_single_codon_changes(
    seq,
    dict_allowed=None,
    dict_allowed_max_min=None,
    frame_offset=0,
    freq_min=0.2,
    forbidden_positions=[],
    codon_usage=codon_usage_ecoli,
):
    """
    dict_allowed[i] = list of allowed TARGET amino acids at codon i
    """
    variants = []

    for i in range(frame_offset, len(seq) - 2, 3):
        if any(pos in forbidden_positions for pos in (i, i+1, i+2)):
            continue

        codon = seq[i:i+3]
        if dict_allowed!=None and (i-frame_offset)//3 in dict_allowed:
            allowed_aas = dict_allowed.get((i-frame_offset)//3, [])
        else:
            allowed_aas=None

        # No restriction → behave as before
        if allowed_aas==None:
            aa = genetic_code.get(codon)
            if aa not in codon_usage:
                continue

            ranked = sorted(
                codon_usage[aa].items(),
                key=lambda x: x[1],
                reverse=True,
            )

            for new_codon, usage in ranked:
                if usage <= freq_min or new_codon == codon:
                    continue
                variants.append(seq[:i] + new_codon + seq[i+3:])

        # Restricted case: AA → compatible codons
        else:
            
            candidate_codons = set(codons_compatible_with_AA(allowed_aas[0]))
            for aa in allowed_aas[1:]:
                candidate_codons &= codons_compatible_with_AA(aa)
            candidate_codons_not_stop=candidate_codons - codons_reaching_stop #remove codons reaching stop codons by A mutagenesis
            if not candidate_codons_not_stop:
                warnings.warn('Every codon allowed here can mutate to a stop codon; keeping them anyway.', stacklevel=2)
            else:
                candidate_codons=candidate_codons_not_stop
            filter_codons=[]
            for new_codon in candidate_codons:
                aa = genetic_code.get(new_codon)
                
                if aa not in codon_usage:
                    continue

                usage = codon_usage[aa].get(new_codon, 0)
                if usage <= freq_min:
                    continue

                if new_codon == codon:
                    continue
                filter_codons.append(new_codon)
            candidate_codons=filter_codons
            if dict_allowed_max_min!=None and (i-frame_offset)//3 in dict_allowed_max_min:
                j=(i-frame_offset)//3
                if dict_allowed_max_min[j]=='max':
                    L=[]
                    for codon in candidate_codons: 
                        L.append(len(get_aa_by_adenine_mutation(codon)))
                    candidate_codons=[candidate_codons[k] for k in range(len(L)) if L[k]==max(L)]
                    
                elif dict_allowed_max_min[j]=='min':
                    L=[]
                    for codon in candidate_codons: 
                        L.append(len(get_aa_by_adenine_mutation(codon)))
                    candidate_codons=[candidate_codons[k] for k in range(len(L)) if L[k]==min(L)]

            for new_codon in candidate_codons:
                variants.append(seq[:i] + new_codon + seq[i+3:])

    return variants

def _evaluate_sequences(variants, plot=False):
    """
    Encode sequences, run classifiers, return list of dicts with scores.
    Set `plot=True` to also draw a scatter plot of the two scores.
    """
    seqs = [v for v in variants]
    Scores=tr_score_list(seqs, #A list of strings of TRs DNA sequences
seqs, #A list of strings of TRs names
features=2)
    Score_TRSp = list(Scores['TR_Score_Sp'])
    Score_TRSpAvd = list(Scores['TR_Score_Avd'])
    if plot:
        plt.figure(figsize=(6,6))
        plt.scatter(Score_TRSp, Score_TRSpAvd, alpha=0.7)
        plt.xlabel("Score_TRSp")
        plt.ylabel("Score_TRSpAvd")
        plt.grid(True)
        plt.show()
    results = []
    for i, seq,  in enumerate(variants):
        results.append({
            "sequence": seq,
            "Score_TRSp": Score_TRSp[i],
            "Score_TRSpAvd": Score_TRSpAvd[i],
            "Score_geo_mean": np.sqrt(Score_TRSp[i] * Score_TRSpAvd[i])
        })
    return results

def _check_any_AAC_position(dict_allowed,dict_allowed_max_min,length):
    if dict_allowed_max_min==None:
        return []
    else:
        if dict_allowed is None: dict_allowed = {}   #asking for 'max' without an AA list is valid
        forbidden_to_add=[]
        for i in range(length):
            if (i in dict_allowed_max_min) and (dict_allowed_max_min[i]=="max") and (not i in dict_allowed):
                forbidden_to_add.append(i)
        return(forbidden_to_add)

In [ ]:
#| hide
# Tests for nt_to_codons, codons_to_aa, nt_prot
assert nt_to_codons('ATGGCATGA') == ['ATG', 'GCA', 'TGA']
assert nt_to_codons('ATGGC') == ['ATG']  # trims extra
assert nt_to_codons('') == []
assert codons_to_aa(['ATG', 'GCA', 'TGA']) == 'MA*'
assert codons_to_aa([]) == ''
assert nt_prot('ATGGCATGA') == 'MA*'

## TR sequence optimization

Beam-search optimization to improve TR sequences while maintaining protein function.

In [ ]:
# | export
def _split_diversify(diversify):
    """Split a `diversify` dict into the (allowed amino acids, max/min) pair used internally.

    Accepted values per codon position:
    - `'max'` / `'min'`            : tie-break only, no constraint on which amino acids are reached
    - `['Y','F']`                  : the codon must be able to reach all of these
    - `('min', ['K','R'])`         : both - must reach these, and among the codons that can,
                                     take the one reaching the fewest (or most) others
    """
    allowed, max_min = {}, {}
    for pos, spec in (diversify or {}).items():
        mode, aas = None, None
        if isinstance(spec, str) and spec in ('max', 'min'):
            mode = spec
        elif (isinstance(spec, tuple) and len(spec) == 2
              and isinstance(spec[0], str) and spec[0] in ('max', 'min')):
            mode, aas = spec[0], spec[1]
            if isinstance(aas, str): aas = [aas]
        elif isinstance(spec, (list, tuple, set)):
            aas = list(spec)
        else:
            raise ValueError(f"diversify[{pos!r}]={spec!r}: expected 'max'/'min', a list of amino "
                             f"acids, or a ('max'|'min', [amino acids]) pair")
        if aas is not None: allowed[pos] = list(aas)
        if mode is not None: max_min[pos] = mode
    return allowed, max_min

In [ ]:
#| export
def optimize_sequence(
    original_seq,
    frame_offset= 0,
    diversify = None,
    dict_allowed_AAs = None,
    dict_allowed_AAs_max_min=None,
    CHANGES = 6,
    freq_min = 0.2,
    N = 1,
    forbidden_positions = None,
    threshold = 0.7,
    codon_usage = codon_usage_ecoli,
    plot = False
):
    """
    Optimize a DNA sequence via synonymous codon substitutions.

    This function performs a beam-search–based optimization of a nucleotide
    sequence by iteratively proposing single-codon synonymous changes and
    evaluating them with the two scoring functions. The search stops early if a
    variant meets the specified score thresholds, otherwise the best Pareto-
    optimal solution is returned.

    Parameters
    ----------
    original_seq : str
        Original DNA sequence to optimize.
    frame_offset : int, default=0
        Reading-frame offset (0, 1, or 2) used when grouping codons.
    diversify : dict, default=None
        What to do at chosen codon positions, keyed by codon index:
        `'max'` or `'min'` alone tunes how many amino acids that position can
        reach, without constraining which (asking for `'max'` with no list puts
        an `AAC` there and locks it); a list of amino acids requires the codon to
        be able to reach all of them; a `('min', ['K','R'])` pair does both -
        reach these, and among the codons that can, take the one that brings
        along the fewest (or most) others.
    dict_allowed_AAs : dict, default=None
        Deprecated, use `diversify`.
        Dictionary of positions (keys) and AAs (values) where you want to reach all AAs in the list with the codon. If not mentioned, does as before.
        Selects for codons which do not reach (by adenine mutation) stop codons. If not possible, allow them anyway.
    dict_allowed_AAs_max_min : dict, default=None
        Deprecated, use `diversify`.
        Dictionary of positions (keys) and either you want maximum diversity ('max') or mimimum diversity ('min')  at the positions mentionned in dict_allowed_AAs. Diversity = number of AAs reachable by adenine mutations (already removed codons reaching stop codons). 
        If not mentioned, any sequence that fullfills dict_allowed_AAs[i] is accepted.
        If there is no list of accessible AAs for dict_allowed_AAs[i] but dict_allowed_AAs_min_max[i]=='max', it puts an AAC here and forbids the algorithm to change it.
    CHANGES : int, default=6
        Maximum number of codon substitutions allowed (on top of the AAs requirements from the previous argument).
    freq_min : float, default=0.2
        Lowest usage frequency acceptable.
    N : int, default=1
        Number of putative TR to output.
    forbidden_positions : list[int], optional
        Nucleotide positions that must not be modified. Note that this is keyed
        by nucleotide, while `dict_allowed_AAs` and `dict_allowed_AAs_max_min`
        are keyed by codon.
    threshold : float, default=0.7
        Minimum required value for both `Score_TRSp` and `Score_TRSpAvd` to
        accept a sequence as optimal.
    codon_usage : dict, optional
        Codon usage table of E. Coli mapping amino acids to codons and frequencies.

    Returns
    -------
    list of dict
        One entry per proposed variant, best first (`N` of them), each
        containing:
        - `Original_Sequence` : str  
          Input DNA sequence.
        - `New_Variant` : str  
          Optimized DNA sequence.
        - `Rank` : int or None  
          rank of the sequence (by score).
        - `Score` : float or None  
          score of the selected variant (geometrical mean).
        - `Score_TRSp` : float or None  
          TR+Sp score of the selected variant.
        - `Score_TRSpAvd` : float or None  
          Avd+TR+Sp score of the selected variant.

    Notes
    -----
    - The algorithm keeps only Pareto-optimal candidates at each iteration.
    - If no variant satisfies the threshold criteria, the best-scoring
      sequence after `CHANGES` iterations is returned.
    - Internal scoring and plotting are handled by `_evaluate_sequences`;
      pass `plot=True` to draw a scatter plot at each round of the search.

    Examples
    --------
    ```python
    variants = optimize_sequence(TR_seq, N=5)
    variants[0]["New_Variant"]
    ```
    """
    if forbidden_positions is None: forbidden_positions = []
    if diversify is not None:
        if dict_allowed_AAs is not None or dict_allowed_AAs_max_min is not None:
            raise ValueError("pass either diversify= or the deprecated dict_allowed_AAs/"
                             "dict_allowed_AAs_max_min, not both")
        dict_allowed_AAs, dict_allowed_AAs_max_min = _split_diversify(diversify)
    elif dict_allowed_AAs is not None or dict_allowed_AAs_max_min is not None:
        warnings.warn("dict_allowed_AAs and dict_allowed_AAs_max_min are deprecated; "
                      "use diversify={pos: 'max'|[AAs]|('max'|'min',[AAs])}.",
                      DeprecationWarning, stacklevel=2)
    codon_changes_done = 0
    if dict_allowed_AAs_max_min==None:
        beam = [original_seq]
        seq=original_seq
        forbidden_final=forbidden_positions
    elif _check_any_AAC_position(dict_allowed_AAs,dict_allowed_AAs_max_min,len(original_seq)//3)!=[]: #Add AAC at positions where you want to maximize diversity but didn't precise the allowed AAs
        forbidden_to_add=_check_any_AAC_position(dict_allowed_AAs,dict_allowed_AAs_max_min,len(original_seq)//3)
        seq=original_seq
        for i in forbidden_to_add:
            if seq[3*i+frame_offset:3*i+3+frame_offset]!="AAC":
                codon_changes_done += 1
            seq=seq[:3*i+frame_offset]+'AAC'+seq[3*i+3+frame_offset:]
        forbidden_to_add=[3*i+frame_offset for i in forbidden_to_add]
        
        beam = _valid_seq_reach_AAs(
                seq,
                dict_allowed=dict_allowed_AAs,
                dict_allowed_max_min=dict_allowed_AAs_max_min,
                frame_offset=frame_offset,
                freq_min=freq_min,
                codon_usage=codon_usage
            )
        forbidden_final=forbidden_positions+forbidden_to_add
    else:
        forbidden_to_add=[]
        beam = _valid_seq_reach_AAs(
                original_seq,
                dict_allowed=dict_allowed_AAs,
                dict_allowed_max_min=dict_allowed_AAs_max_min,
                frame_offset=frame_offset,
                freq_min=freq_min,
                codon_usage=codon_usage
            )
        seq=original_seq
        forbidden_final=forbidden_positions
                    
    evaluated = _evaluate_sequences(beam, plot=plot)

    good = [
        v for v in evaluated
        if v["Score_TRSp"] >= threshold and v["Score_TRSpAvd"] >= threshold
    ]
    if good and N>=len(evaluated):
        best = max(good, key=lambda x: x["Score_geo_mean"])
        return [{
            "Original_Sequence": original_seq,
            "New_Variant": best["sequence"],
            "Score": best['Score_geo_mean'],
            "Rank":1,
            "Score_TRSp": best["Score_TRSp"],
            "Score_TRSpAvd": best["Score_TRSpAvd"]
        }]

    
    while beam and codon_changes_done <= CHANGES:
        codon_changes_done += 1
        variants = []
        for seq in beam:
            variants.extend(
                _propose_single_codon_changes(
                    seq,dict_allowed_AAs,dict_allowed_AAs_max_min, frame_offset, freq_min,
                    forbidden_final, codon_usage
                )
            )

        variants = np.unique(variants)
        evaluated = _evaluate_sequences(variants, plot=plot)
        good = [
            v for v in evaluated
            if v["Score_TRSp"] >= threshold and v["Score_TRSpAvd"] >= threshold
        ]
        if good:
            good.sort(key=lambda x: x["Score_geo_mean"], reverse=True)
            selected = good[:N]
        
            # 2) if fewer than N, fill with best overall
            if len(selected) < N:
                remaining = [
                    v for v in evaluated
                    if v["sequence"] not in {s["sequence"] for s in selected}
                ]
                remaining.sort(key=lambda x: x["Score_geo_mean"], reverse=True)
                selected.extend(remaining[: N - len(selected)])
        
            # 3) format output
            return [
                {
                    "Original_Sequence": original_seq,
                    "New_Variant": v["sequence"],
                    "Score": v["Score_geo_mean"],
                    "Rank": i+1,
                    "Score_TRSp": v["Score_TRSp"],
                    "Score_TRSpAvd": v["Score_TRSpAvd"],
                }
                for i,v in enumerate(selected)
            ]
        evaluated.sort(key=lambda x: x["Score_geo_mean"], reverse=True)
        # Keep only Pareto-optimal variants
        pareto_variants = pareto_front(evaluated)

        # Optional: still restrict beam size if too many
        pareto_variants.sort(key=lambda x: x["Score_geo_mean"], reverse=True)
        beam = [v["sequence"] for v in pareto_variants[:40]]
    selected=[]
    evaluated.sort(key=lambda x: x["Score_geo_mean"], reverse=True)

    remaining = [
                    v for v in evaluated
                    if v["sequence"] not in {s["sequence"] for s in selected}
                ]
    remaining.sort(key=lambda x: x["Score_geo_mean"], reverse=True)
    selected.extend(remaining[: N - len(selected)])
        
            # 3) format output
    return [
        {
            "Original_Sequence": original_seq,
            "New_Variant": v["sequence"],
            "Score": v["Score_geo_mean"],
            "Rank": i+1,
            "Score_TRSp": v["Score_TRSp"],
            "Score_TRSpAvd": v["Score_TRSpAvd"],
        }
        for i,v in enumerate(selected)
    ]

In [ ]:
seq = 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'
dict_allowed={0:['D','Y'],1:['T']}
dict_allowed_max_min={0:'max'}
optimize_sequence(seq,N=5,CHANGES=6,dict_allowed_AAs=dict_allowed,dict_allowed_AAs_max_min=dict_allowed_max_min)

[{'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACGTGCTATGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAAGCACATC'),
  'Score': np.float64(0.8146164741766521),
  'Rank': 1,
  'Score_TRSp': 0.79,
  'Score_TRSpAvd': 0.84},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACCTGCTACGGACTGAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6462197768561405),
  'Rank': 2,
  'Score_TRSp': 0.58,
  'Score_TRSpAvd': 0.72},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACCTGCTACGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6440496875241848),
  'Rank': 3,
  'Score_TRSp': 0.61,
  'Score_TRSpAvd': 0.68},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACCTGCTACGGCTTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6426507605223851),
  'Rank': 4,
  'Score_TRSp': 0.59,
  'Score_TRSpAvd': 0.7},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACGTGCTACGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6409368143584826),
  'Rank': 5,
  'Score_TRSp': 0.52,
  'Score_TRSpAvd': 0.79}]

In [ ]:
seq = 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'
dict_allowed={0:['D','Y'],1:['T']}
dict_allowed_max_min={1:'min'}
optimize_sequence(seq,N=5,CHANGES=6,dict_allowed_AAs=dict_allowed,dict_allowed_AAs_max_min=dict_allowed_max_min)

[{'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACGTGCTATGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAAGCACATC'),
  'Score': np.float64(0.8146164741766521),
  'Rank': 1,
  'Score_TRSp': 0.79,
  'Score_TRSpAvd': 0.84},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AATACGTGCTATGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAAGCACATC'),
  'Score': np.float64(0.8146164741766521),
  'Rank': 2,
  'Score_TRSp': 0.79,
  'Score_TRSpAvd': 0.84},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACCTGCTACGGACTGAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6462197768561405),
  'Rank': 3,
  'Score_TRSp': 0.58,
  'Score_TRSpAvd': 0.72},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAACCTGCTACGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6440496875241848),
  'Rank': 4,
  'Score_TRSp': 0.61,
  'Score_TRSpAvd': 0.68},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AATACGTGCTACGGATTAAAACGCCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'),
  'Score': np.float64(0.6429618962271404),
  'Rank': 5,
  'Score_TRSp': 0.53,
  'Score_TRSpAvd': 0.78}]

In [ ]:
seq = 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'
dict_allowed={0:['D','Y']}
dict_allowed_max_min={1:'max'}
optimize_sequence(seq,N=5,CHANGES=6,dict_allowed_AAs=dict_allowed,dict_allowed_AAs_max_min=dict_allowed_max_min)

[{'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAAACTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGTACCTAACTGCAGGCCCATC'),
  'Score': np.float64(0.7942291860665912),
  'Rank': 1,
  'Score_TRSp': 0.83,
  'Score_TRSpAvd': 0.76},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAAACTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTGCCAGGTCGCGGCACCTAACTGCAGGCCCATC'),
  'Score': np.float64(0.7942291860665912),
  'Rank': 2,
  'Score_TRSp': 0.83,
  'Score_TRSpAvd': 0.76},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAAACTGCTACGGTTTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCGCATC'),
  'Score': np.float64(0.781408983823452),
  'Rank': 3,
  'Score_TRSp': 0.86,
  'Score_TRSpAvd': 0.71},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAAACTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTTCCAGGTCGCGGCACCTAACTGCAGGCCCATC'),
  'Score': np.float64(0.7745966692414834),
  'Rank': 4,
  'Score_TRSp': 0.8,
  'Score_TRSpAvd': 0.75},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('AAAAACTGTTATGGTTTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCCCATC'),
  'Score': np.float64(0.7676587783644501),
  'Rank': 5,
  'Score_TRSp': 0.83,
  'Score_TRSpAvd': 0.71}]

In [ ]:
seq = 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC'
optimize_sequence(seq,N=5,CHANGES=6)

[{'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('GACACCTGTTATGGTTTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCGCATC'),
  'Score': np.float64(0.7622335600063802),
  'Rank': 1,
  'Score_TRSp': 0.83,
  'Score_TRSpAvd': 0.7},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('GACACCTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGTACCTAACTGCAGGCGCATC'),
  'Score': np.float64(0.7341661937191061),
  'Rank': 2,
  'Score_TRSp': 0.77,
  'Score_TRSpAvd': 0.7},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('GACACCTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGTGGCACCTAACTGCAGGCGCATC'),
  'Score': np.float64(0.7341661937191061),
  'Rank': 3,
  'Score_TRSp': 0.77,
  'Score_TRSpAvd': 0.7},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('GACACCTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTGCCAGGTCGCGGCACCTAACTGCAGGCGCATC'),
  'Score': np.float64(0.7341661937191061),
  'Rank': 4,
  'Score_TRSp': 0.77,
  'Score_TRSpAvd': 0.7},
 {'Original_Sequence': 'GACACCTGCTATGGATTAAAAAGGCGCTCCCGTTGGGTACCAGGTCGCGGCACCTAACTGCAGGCACATC',
  'New_Variant': np.str_('GACACCTGTTATGGATTAAAAAGGCGCTCCCGTTGGGTTCCAGGTCGCGGCACCTAACTGCAGGCGCATC'),
  'Score': np.float64(0.7341661937191061),
  'Rank': 5,
  'Score_TRSp': 0.77,
  'Score_TRSpAvd': 0.7}]

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()